# Generated by Django 2.1.3 on 2018-11-27 14:21

import apps.movies.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.movies.models.movie_image_path),
        ),
    ]
