# Generated by Django 2.1.3 on 2018-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20181128_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
